#!/usr/bin/env python3
"""
EVO-Bot Telegram Setup & Launcher
=================================
One-command setup for running EVO-Bot on Telegram.

Usage:
    python setup_telegram.py          # Interactive setup
    python setup_telegram.py --check  # Check configuration only
    python setup_telegram.py --run   # Run bot (after setup)
"""
import sys
import os
import subprocess
import argparse
from pathlib import Path

FORGE_BOT_DIR = Path(__file__).parent
ENV_FILE = FORGE_BOT_DIR / ".env"
ENV_EXAMPLE = FORGE_BOT_DIR / ".env.example"


def print_banner():
    print("""
    ╔═══════════════════════════════════════════════════════════╗
    ║                                                           ║
    ║   🤖 EVO-BOT Telegram Setup                               ║
    ║   ═══════════════════════════════════════                 ║
    ║                                                           ║
    ╚═══════════════════════════════════════════════════════════╝
    """)


def check_python_telegram():
    """Check if python-telegram-bot is installed."""
    try:
        import telegram
        return True
    except ImportError:
        return False


def check_ollama():
    """Check if Ollama is running."""
    host = os.environ.get("OLLAMA_HOST", "127.0.0.1:11434")
    try:
        import requests
        resp = requests.get(f"http://{host}/api/tags", timeout=5)
        return resp.status_code == 200
    except Exception:
        return False


def check_env():
    """Check .env file configuration."""
    if not ENV_FILE.exists():
        return {"exists": False, "token": False, "model": False}
    
    token = None
    model = None
    with open(ENV_FILE, "r") as f:
        for line in f:
            if line.startswith("TELEGRAM_BOT_TOKEN="):
                token = line.split("=", 1)[1].strip()
            if line.startswith("OLLAMA_MODEL="):
                model = line.split("=", 1)[1].strip()
    
    return {
        "exists": True,
        "token": token and token != "YOUR_BOT_TOKEN_HERE" and len(token) > 10,
        "token_value": token if token else "",
        "model": model or "qwen2.5:7b"
    }


def create_env_interactive():
    """Create .env file interactively."""
    print("\n📋 Let's configure your Telegram bot...")
    print("\n1. Open Telegram and search for @BotFather")
    print("2. Send: /newbot")
    print("3. Choose a name (e.g., 'EVO Bot')")
    print("4. Choose a username (e.g., 'evo_forge_bot') - must end in 'bot'")
    print("5. Copy the token BotFather gives you")
    print()
    
    token = input("🔑 Paste your TELEGRAM_BOT_TOKEN: ").strip()
    
    if not token or len(token) < 20:
        print("❌ Invalid token. Please get a real token from @BotFather")
        return False
    
    # Ask for allowed users
    users = input("👥 Enter allowed Telegram user IDs (comma-separated, or leave empty for all): ").strip()
    
    # Ask for Ollama model
    default_model = "qwen2.5:7b"
    model = input(f"🧠 Ollama model [{default_model}]: ").strip()
    if not model:
        model = default_model
    
    # Write .env
    env_content = f"""# EVO-Bot Configuration
# Generated by setup_telegram.py

OLLAMA_HOST=127.0.0.1:11434
OLLAMA_MODEL={model}

TELEGRAM_BOT_TOKEN={token}
TELEGRAM_ALLOWED_USERS={users}
"""
    
    with open(ENV_FILE, "w") as f:
        f.write(env_content)
    
    print(f"✅ Configuration saved to {ENV_FILE}")
    print(f"   Model: {model}")
    print(f"   Allowed users: {users if users else 'ALL'}")
    return True


def install_dependencies():
    """Install required packages."""
    print("\n📦 Installing dependencies...")
    deps = ["python-telegram-bot", "requests"]
    for dep in deps:
        print(f"   Installing {dep}...")
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", dep],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            print(f"   ⚠️  {dep} install failed: {result.stderr[:100]}")
        else:
            print(f"   ✅ {dep} installed")


def run_bot():
    """Launch the Telegram bot."""
    telegram_bot = FORGE_BOT_DIR / "telegram_bot.py"
    if not telegram_bot.exists():
        print("❌ telegram_bot.py not found!")
        return 1
    
    print("\n🚀 Starting EVO-Bot Telegram interface...")
    print("   Press Ctrl+C to stop\n")
    
    # Load .env manually
    if ENV_FILE.exists():
        with open(ENV_FILE, "r") as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    key, val = line.strip().split("=", 1)
                    os.environ[key] = val
    
    try:
        subprocess.run([sys.executable, str(telegram_bot)], cwd=str(FORGE_BOT_DIR))
    except KeyboardInterrupt:
        print("\n👋 Bot stopped.")
    return 0


def main():
    parser = argparse.ArgumentParser(description="EVO-Bot Telegram Setup")
    parser.add_argument("--check", action="store_true", help="Check configuration only")
    parser.add_argument("--run", action="store_true", help="Run bot immediately")
    args = parser.parse_args()
    
    print_banner()
    
    # Check mode
    if args.check:
        print("🔍 Checking configuration...")
        env = check_env()
        tg = check_python_telegram()
        ollama = check_ollama()
        
        print(f"   .env file: {'✅' if env['exists'] else '❌ Not found'}")
        if env['exists']:
            print(f"   Bot token: {'✅ Configured' if env['token'] else '❌ Missing/invalid'}")
        print(f"   python-telegram-bot: {'✅' if tg else '❌ Not installed'}")
        print(f"   Ollama running: {'✅' if ollama else '❌ Not reachable'}")
        return 0 if (env['token'] and tg and ollama) else 1
    
    # Run mode
    if args.run:
        env = check_env()
        if not env['token']:
            print("❌ No valid TELEGRAM_BOT_TOKEN found. Run without --run to setup.")
            return 1
        return run_bot()
    
    # Interactive setup mode
    print("Welcome to EVO-Bot Telegram setup!\n")
    
    # Check Ollama
    print("🧠 Checking Ollama...")
    if check_ollama():
        print("   ✅ Ollama is running")
    else:
        print("   ⚠️  Ollama not detected at 127.0.0.1:11434")
        print("      Make sure Ollama is running: ollama serve")
    
    # Check dependencies
    print("\n📦 Checking dependencies...")
    if check_python_telegram():
        print("   ✅ python-telegram-bot installed")
    else:
        print("   ❌ python-telegram-bot not installed")
        install = input("   Install now? [Y/n]: ").strip().lower()
        if install in ("", "y", "yes"):
            install_dependencies()
    
    # Check .env
    env = check_env()
    print("\n🔑 Checking Telegram configuration...")
    if env['exists']:
        print(f"   .env file found")
        if env['token']:
            print(f"   ✅ Bot token configured")
            run_now = input("\n🚀 Run bot now? [Y/n]: ").strip().lower()
            if run_now in ("", "y", "yes"):
                return run_bot()
            return 0
        else:
            print("   ❌ Bot token missing or invalid")
    else:
        print("   ❌ .env file not found")
    
    # Create .env
    print("\n📋 Let's create configuration...")
    if create_env_interactive():
        run_now = input("\n🚀 Run bot now? [Y/n]: ").strip().lower()
        if run_now in ("", "y", "yes"):
            return run_bot()
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
